name: ZeroHunter
version: '1.0'
main: me.lavainmc.zerohunter.ZeroHunter
api-version: '1.21'
authors: [ Lavainmc ]
description: Plugin for End of Minecraft ManHunt
website: ""

commands:
  zerohunter:
    description: ZeroHunter游戏主命令
    usage: /<command> <start|stop|status|setrole>
    permission: zerohunter.command.use
    permission-message: 你没有权限使用此命令

permissions:
  zerohunter.command.use:
    description: 允许使用ManHunt基础命令
    default: true
  zerohunter.command.admin:
    description: ManHunt管理员权限
    default: op