name: ZeroHunt
version: '1.0'
main: me.lavainmc.zerohunt.ZeroHunt
api-version: '1.21'
authors: [ Lavainmc ]
description: Plugin for End of Minecraft ManHunt
website: ""

commands:
  zerohunt:
    description: ZeroHunt插件主命令
    usage: /<command> <start|stop|status|setrole>
    permission: zerohunt.command.use
    permission-message: ""§c你没有权限使用此命令"

permissions:
  zerohunt.command.use:
    description: 允许使用ZeroHunt基础命令
    default: true
  zerohunt.command.admin:
    description: ZeroHunt管理员命令权限
    default: op